In [5]:
# Author: Roi Yehoshua <roiyeho@gmail.com>
# Date: February 2024
# License: MIT

In [10]:
import numpy as np

In [12]:
from sklearn.preprocessing import PolynomialFeatures

X = np.array([[0, 1], [2, 3], [4, 5]])
poly_features = PolynomialFeatures(degree=2)
X_new = poly_features.fit_transform(X)
print(X_new)

[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]
