In [1]:
import numpy as np

In [2]:
# Create a 1-D array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [7]:
a[1]

2

In [8]:
a[1] = 5
a

array([1, 5, 3])

In [14]:
# Create a 2-D array
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.shape

(2, 3)

In [16]:
b[0, 1]

2

In [17]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [19]:
a = np.array([1, 2, 3], dtype='uint8')
a.dtype

dtype('uint8')

In [3]:
a = np.array([1.2, 5, 3.92, 4.5])
a.astype(int)

array([1, 5, 3, 4])

In [28]:
a = np.zeros((3, 3))  # a matrix 3x3 of all zeros
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
b = np.ones(5)  # a 1-D array of all ones
b

array([1., 1., 1., 1., 1.])

In [30]:
c = np.full((2, 2), 7)  # a constant array 2x2 with values = 7
c

array([[7, 7],
       [7, 7]])

In [43]:
np.random.random((3, 3))

array([[0.53938706, 0.48493127, 0.6644849 ],
       [0.9244017 , 0.12693321, 0.0937883 ],
       [0.11086629, 0.46859553, 0.77811775]])

In [44]:
np.random.randint(1, 10, 5)

array([3, 1, 7, 2, 3])

In [47]:
np.random.normal(size=(3, 3))

array([[-0.25329196, -0.0870325 ,  1.77494967],
       [ 1.36233034, -1.04551834, -0.16560166],
       [ 1.04324528, -2.18187512, -1.33373651]])

In [48]:
np.random.normal(100, 10, size=(3, 3))

array([[ 71.33579679,  88.46795444, 105.73253249],
       [ 94.35509741, 102.48275919,  86.61720805],
       [ 90.20942587, 103.56148269, 104.07765674]])

In [37]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(0.0, 1.0, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [38]:
np.linspace(0, np.pi, 10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [31]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a.reshape(3, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a[1, 2]

6

In [58]:
a[-1, -1] = 10  # can use negative indexes
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [59]:
a[1]  # get the second row

array([4, 5, 6])

In [60]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a[0:2, 0:2]  # the first two rows and two columns

array([[1, 2],
       [4, 5]])

In [64]:
a[0:2, 1]  # the first two rows and the second column

array([2, 5])

In [65]:
a[:, 1]  # the second column

array([2, 5, 8])

In [66]:
a[1, 1:]  # the second row and second column onwards

array([5, 6])

In [6]:
a = np.arange(5)
a[a % 2 == 0]

array([0, 2, 4])

In [7]:
a % 2 == 0

array([ True, False,  True, False,  True])

In [8]:
a[[True, True, False, False, True]]

array([0, 1, 4])

In [12]:
a = np.random.randint(100, size=10)
a

array([37,  5, 92, 40,  4, 89, 48, 38, 17, 65])

In [13]:
a[[3, 7, 2]]

array([40, 38, 92])

In [14]:
# the same as
np.array([a[3], a[7], a[2]])

array([40, 38, 92])

In [25]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
a[[0, 1, 2], [2, 1, 3]]

array([ 3,  6, 12])

In [27]:
# the same as
np.array([a[0, 2], a[1, 1], a[2, 3]])

array([ 3,  6, 12])

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[[2, 1, 8, 4]] = 99
a

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [36]:
a[a < 5] = -1
a

array([-1, 99, 99, -1, 99,  5,  6,  7, 99,  9])

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b

array([5, 7, 9])

In [6]:
2 * a

array([2, 4, 6])

In [4]:
def compute_reciprocals(values):
    result = np.empty(len(values))
    for i in range(len(values)):
        result[i] = 1.0 / values[i]
    return result

big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.53 s ± 25.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit (1.0 / big_array)

3.61 ms ± 16.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [14]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [15]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [16]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [30]:
x = [1, 2, 3]
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [31]:
x = [1, 2, 4, 10]
np.log(x)  # ln(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [32]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [33]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [44]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
a.sum()  # sum the entire array

78

In [48]:
a.sum(axis=0)  # find the sum of each column

array([15, 18, 21, 24])

In [49]:
a.sum(axis=1)  # find the sum of each row

array([10, 26, 42])

In [18]:
a = np.random.randint(0, 10, (3, 3))
a

array([[7, 6, 3],
       [5, 2, 8],
       [6, 9, 9]])

In [19]:
a.argmin()

4

In [20]:
a.argmin(axis=0)

array([1, 1, 0], dtype=int64)

In [21]:
a.argmin(axis=1)

array([2, 1, 0], dtype=int64)

In [9]:
a = np.array([1, np.nan, 3, 4])
a

array([ 1., nan,  3.,  4.])

In [8]:
np.isnan(a)

array([False,  True, False, False])

In [10]:
a + 1

array([ 2., nan,  4.,  5.])

In [13]:
a.sum()

nan

In [12]:
np.nansum(a)

8.0

In [8]:
a = np.array([1, 2, 3, 4, 5])

In [9]:
a < 3

array([ True,  True, False, False, False])

In [10]:
a == 3

array([False, False,  True, False, False])

In [5]:
2 * a == a**2

array([False,  True, False, False, False])

In [13]:
x = np.linspace(0, np.pi, 5)

In [15]:
np.sin(x)**2 == (1 - np.cos(x)**2)

array([ True, False,  True,  True, False])

In [16]:
np.isclose(np.sin(x)**2, 1 - np.cos(x)**2)

array([ True,  True,  True,  True,  True])

In [23]:
a = np.array([1, 2, 3, 4, 5])

In [29]:
(a > 1) & (a < 4)

array([False,  True,  True, False, False])

In [30]:
(a < 2) | (a > 4)

array([ True, False, False, False,  True])

In [26]:
~(a > 3)

array([ True,  True,  True, False, False])

In [41]:
a = np.random.randint(100, size=(3, 4))
a

array([[51, 25, 56,  5],
       [97, 87, 35,  5],
       [28, 25, 72, 29]])

In [42]:
np.count_nonzero(a % 2 == 0)

3

In [43]:
np.count_nonzero(a % 2 == 0, axis=0)

array([1, 0, 2, 0], dtype=int64)

In [44]:
np.count_nonzero(a % 2 == 0, axis=1)

array([1, 0, 2], dtype=int64)

In [45]:
a = np.random.randint(100, size=(3, 4))
a

array([[87, 99, 81, 78],
       [84, 53, 81, 73],
       [68, 51, 43, 47]])

In [47]:
# are there any values less than 10?
np.any(a < 10)

False

In [48]:
# are all values greater than 20?
np.all(a > 20)

True

In [49]:
# are all values in each row greater than 50?
np.all(a > 50, axis=1)

array([ True,  True, False])

In [58]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit sorted(big_array)

308 ms ± 5.53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
%timeit np.sort(big_array)

30.7 ms ± 906 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [60]:
a = np.array([3, 1, 4, 2, 5])
np.sort(a)

array([1, 2, 3, 4, 5])

In [61]:
a

array([3, 1, 4, 2, 5])

In [62]:
a.sort()
a

array([1, 2, 3, 4, 5])

In [68]:
a = np.random.randint(10, size=(4, 6))
a

array([[0, 3, 1, 5, 8, 3],
       [9, 1, 5, 9, 1, 6],
       [4, 5, 4, 0, 8, 9],
       [9, 7, 5, 0, 5, 6]])

In [69]:
# Sort each column of a
np.sort(a, axis=0)

array([[0, 1, 1, 0, 1, 3],
       [4, 3, 4, 0, 5, 6],
       [9, 5, 5, 5, 8, 6],
       [9, 7, 5, 9, 8, 9]])

In [70]:
# Sort each row of a
np.sort(a, axis=1)

array([[0, 1, 3, 3, 5, 8],
       [1, 1, 5, 6, 9, 9],
       [0, 4, 4, 5, 8, 9],
       [0, 5, 5, 6, 7, 9]])

In [3]:
a = [7, 3, 10, 2, 8]
np.argsort(a)

array([3, 1, 0, 4, 2], dtype=int64)

In [80]:
a = np.array([7, 2, 5, 1, 4, 6, 3])
np.partition(a, 3)

array([2, 1, 3, 4, 5, 6, 7])

In [81]:
np.argpartition(a, 3)

array([1, 3, 6, 4, 2, 5, 0], dtype=int64)

In [83]:
a = np.array([7, 2, 5, 1, 4, 6, 3])
np.where(a > 4)

(array([0, 2, 5], dtype=int64),)

In [85]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
np.where(a > 4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [5]:
a = np.array([1, 2, 6, 4, 2, 3, 2, 6])
np.unique(a)

array([1, 2, 3, 4, 6])

In [6]:
values, counts = np.unique(a, return_counts=True)
counts

array([1, 3, 1, 1, 2], dtype=int64)

In [93]:
a = np.array([1, 2, 3])
np.append(a, [4, 5])

array([1, 2, 3, 4, 5])

In [94]:
b = np.arange(9).reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
np.append(b, [[9, 10, 11]], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.hstack((a, b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
x = np.array([1, 2])
y = np.array([3, 4])

np.dot(x, y)  # 1 * 3 + 2 * 4

11

In [6]:
A = np.array([[4, 1], [2, 2]])
B = np.array([[1, 0], [0, 1]])

A @ B   # matrix multilpication

array([[4, 1],
       [2, 2]])

In [7]:
A @ x   # matrix-vector multiplication

array([6, 6])