In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(np.sum(x))                     # Sum of all elements
print(np.mean(x, axis=0))            # Mean of each column
print(np.max(x, axis=1))             # Max of each row
print(np.all(x > 0))                 # Are all elements positive?
print(np.any(x > 4, axis=1))         # Are any elements > 4 in each row?
print(np.cumsum(x, axis=1))          # Cumulative row sums
print(np.percentile(x, 25, axis=0))  # 25th percentile per column
print(np.count_nonzero(x % 2 == 0))  # Count of even numbers

78
[5. 6. 7. 8.]
[ 4  8 12]
True
[False  True  True]
[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]
[3. 4. 5. 6.]
6


Keepdims

In [3]:
A = np.array([[1, 2, 3, 4],
              [5, 5, 6, 6],
              [0, 5, 10, 15]])

row_means = A.mean(axis=1, keepdims=True)
centered = A - row_means
centered

array([[-1.5, -0.5,  0.5,  1.5],
       [-0.5, -0.5,  0.5,  0.5],
       [-7.5, -2.5,  2.5,  7.5]])

Combining aggregations

In [4]:
def count_rows_containing(arr, value):
    return np.count_nonzero(np.any(arr == value, axis=1))

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [2, 8, 9],
              [10, 11, 12]])

print(count_rows_containing(A, 2))

2


Detecting Missing Values

In [6]:
x = np.array([1, 2, np.nan, 4])
print(np.isnan(x))

[False False  True False]


Handling Missing Values

In [7]:
x = np.array([1, 2, np.nan, 4, 5])

print(np.sum(x))      # Output: nan
print(np.nansum(x))   # Output: 12.0 (ignores nan)

print(np.mean(x))     # Output: nan
print(np.nanmean(x))  # Output: 3.0

print(np.max(x))      # Output: nan
print(np.nanmax(x))   # Output: 5.0

nan
12.0
nan
3.0
nan
5.0
