In [1]:
import numpy as np

In [2]:
x = np.array([2, 3, 5, 1, 8])
x

array([2, 3, 5, 1, 8])

In [3]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

Data Types

In [4]:
x.dtype

dtype('int32')

In [5]:
x.itemsize

4

In [6]:
x.nbytes

20

In [7]:
x = np.array([1, 2, 3, 4, 5], dtype='int16')
x

array([1, 2, 3, 4, 5], dtype=int16)

In [8]:
x = np.array([1, 2, 3])
x_float = x.astype(np.float32)
x_float

array([1., 2., 3.], dtype=float32)

Array Dimensions and Shape

In [9]:
x = np.array([1, 2, 3, 4, 5])
print(x.shape)

(5,)


In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A.shape)

(2, 3)


In [11]:
T = np.array([[
                [1, 2, 3],
                [4, 5, 6]
              ],
              [
                [7, 8, 9],
                [10, 11, 12]
             ]])
print(T.shape)

(2, 2, 3)


Reshaping an Array

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x = np.array([1, 2, 3, 4])
x.reshape((-1, 1))

array([[1],
       [2],
       [3],
       [4]])

In [14]:
x = np.array([1, 2, 3, 4])
print(x.shape)
print(x.T.shape)  # no change

(4,)
(4,)


Memory Layout

In [15]:
A = np.arange(6).reshape(2, 3)
print(f'A.shape: {A.shape}, A.strides: {A.strides}')

A.shape: (2, 3), A.strides: (12, 4)


In [16]:
B = A.T
print(f'B.shape: {B.shape}, B.strides: {B.strides}')

A[0, 0] = 10
print('A:\n', A)
print('B:\n', B)  # Reflects the change

B.shape: (3, 2), B.strides: (4, 12)
A:
 [[10  1  2]
 [ 3  4  5]]
B:
 [[10  3]
 [ 1  4]
 [ 2  5]]


In [17]:
x = np.array([10, 20, 30, 40, 50])
y = x[[0, 2, 3]]  # Copy: selected elements are gathered into a new array

x[0] = 999
print('x:', x)
print('y:', y)  # Unchanged

x: [999  20  30  40  50]
y: [10 30 40]
