In [1]:
import numpy as np

Sorting Arrays

In [2]:
x = np.array([3, 1, 4, 2, 5])
print(np.sort(x))  # Create a new sorted array
print(x)  # Original unchanged

[1 2 3 4 5]
[3 1 4 2 5]


In [3]:
x.sort()  # Sort in place
print(x)

[1 2 3 4 5]


In [4]:
A = np.array([[3, 1, 4],
              [2, 5, 0]])

print(np.sort(A, axis=0))  # Sort each column
print(np.sort(A, axis=1))  # Sort each row

[[2 1 0]
 [3 5 4]]
[[1 3 4]
 [0 2 5]]


In [5]:
A = np.array([[3, 1, 4],
              [2, 5, 0]])

print(np.argsort(A, axis=0))  # indices to sort each column
print(np.argsort(A, axis=1))  # indices to sort each row

[[1 0 1]
 [0 1 0]]
[[1 0 2]
 [2 0 1]]


In [6]:
x = np.array([5, 2, 3, 2])
labels = np.array(['a', 'b', 'c', 'd'])  # Associate labels with each element
indices = np.argsort(x, kind='mergesort')
print(x[indices])       # Sorted values
print(labels[indices])  # Corresponding original labels

[2 2 3 5]
['b' 'd' 'c' 'a']


Joining Arrays

In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.vstack((a, b))  # Stack vertically (along rows)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a = np.array([[1], [2]])
b = np.array([[3], [4]])

np.hstack((a, b))  # Stack horizontally (along columns)

array([[1, 3],
       [2, 4]])

In [10]:
x = np.array([1, 2])
y = np.array([3, 4])

np.stack((x, y), axis=1)  # Stack as columns into a 2D array

array([[1, 3],
       [2, 4]])

In [11]:
np.hstack((x, y))

array([1, 2, 3, 4])

In [12]:
x = np.array([1, 2])
y = np.array([3, 4])

np.column_stack((x, y))  # Stack as columns into a 2D array

array([[1, 3],
       [2, 4]])

In [13]:
x = np.array([1, 2])
y = np.array([3, 4])

np.c_[x, y]  # Stack as columns into a 2D array

array([[1, 3],
       [2, 4]])

In [14]:
np.c_[1:4, [0, 0, 0]]

array([[1, 0],
       [2, 0],
       [3, 0]])

Splitting Arrays

In [15]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

np.split(a, 2, axis=1)  # Split into 2 subarrays along columns

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [16]:
np.array_split(a, 3, axis=1)  # Uneven split into 3 subarrays along columns

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [17]:
np.vsplit(a, 2)  # Split into 2 row subarrays (along axis 0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [18]:
np.hsplit(a, 2)  # Split into 2 column subarrays (along axis 1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

Adding and Removing Elements

In [19]:
a = np.array([[1, 2], [3, 4]])

np.append(a, [[5, 6]], axis=0)  # Append a new row

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
np.insert(a, 1, [9, 9], axis=0)  # Insert a row at index 1

array([[1, 2],
       [9, 9],
       [3, 4]])

In [21]:
np.delete(a, 0, axis=1)  # Delete the first column

array([[2],
       [4]])

Repeating and Tiling Arrays

In [22]:
x = np.array([1, 2, 3])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3])

In [23]:
np.repeat(x, [1, 2, 3])

array([1, 2, 2, 3, 3, 3])

In [24]:
np.tile(x, 2)

array([1, 2, 3, 1, 2, 3])

In [25]:
A = np.array([[1, 2], [3, 4]])
np.tile(A, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

Rearranging Elements

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])

np.reshape(a, (3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
np.flip(a, axis=1)  # Reverse columns

array([[3, 2, 1],
       [6, 5, 4]])

In [28]:
np.roll(a, shift=1, axis=0)  # Roll rows down by 1

array([[4, 5, 6],
       [1, 2, 3]])

In [29]:
np.transpose(a)  # or simply a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
T = np.ones((2, 3, 4))
np.transpose(T, (1, 0, 2))  # Swap axes 0 and 1 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Changing the Number of Dimensions

In [31]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [32]:
np.expand_dims(a, axis=0)  # Add new axis at position 0

array([[1, 2, 3]])

In [33]:
a[:, np.newaxis]  # Add new axis to make column vector

array([[1],
       [2],
       [3]])

In [34]:
b = np.array([[[1], [2], [3]]])  # Shape (1, 3, 1)
np.squeeze(b)  # Squeeze axes 0 and 2

array([1, 2, 3])