In [1]:
import numpy as np

In [2]:
x = np.array([2, 3, 5, 1, 8])
x

array([2, 3, 5, 1, 8])

In [3]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

Data Types

In [4]:
x.dtype

dtype('int32')

In [5]:
x.itemsize

4

In [6]:
x.nbytes

20

In [7]:
x = np.array([1, 2, 3, 4, 5], dtype='int16')
x

array([1, 2, 3, 4, 5], dtype=int16)

In [8]:
x = np.array([1, 2, 3])
x_float = x.astype(np.float32)
x_float

array([1., 2., 3.], dtype=float32)

Array Dimensions and Shape

In [9]:
x = np.array([1, 2, 3, 4, 5])
print(x.shape)   
print(x.ndim)

(5,)
1


In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A.shape)
print(A.ndim)

(2, 3)
2


In [11]:
T = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[7, 8, 9],
               [10, 11, 12]]])
print(T.shape)
print(T.ndim)

(2, 2, 3)
3


Reshaping an Array

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x = np.array([1, 2, 3, 4])
x.reshape((-1, 1))

array([[1],
       [2],
       [3],
       [4]])

In [14]:
x = np.array([1, 2, 3, 4])
print(x.shape)
print(x.T.shape)  # no change in shape

(4,)
(4,)


Views and Copies

In [15]:
a = np.array([1, 2, 3])
b = np.asarray(a)   # Typically returns a view
b[0] = 99

print('a =', a)
print('b =', b)

a = [99  2  3]
b = [99  2  3]


In [16]:
a = np.array([1, 2, 3])
b = np.copy(a)   # Returns a copy
b[0] = 99

print('a =', a)
print('b =', b)

a = [1 2 3]
b = [99  2  3]


In [17]:
a = np.array([1, 2, 3])
b = np.array(a, copy=False)  # Typically returns a view
b[0] = 99

print('a =', a)
print('b =', b)

a = [99  2  3]
b = [99  2  3]
