In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
x + 10

array([11, 12, 13])

In [3]:
A = np.arange(15).reshape(5, 3)
B = np.array([100, 200, 300])  # shape: (3,)
A + B  # shape: (5, 3), B is broadcast along the first axis

array([[100, 201, 302],
       [103, 204, 305],
       [106, 207, 308],
       [109, 210, 311],
       [112, 213, 314]])

In [4]:
A = np.ones((2, 3, 4))
B = np.array([[10], [20], [30]])  # shape: (3, 1)
A + B  # shape: (2, 3, 4), B is broadcast along the first and last axes

array([[[11., 11., 11., 11.],
        [21., 21., 21., 21.],
        [31., 31., 31., 31.]],

       [[11., 11., 11., 11.],
        [21., 21., 21., 21.],
        [31., 31., 31., 31.]]])

In [5]:
A = np.ones((3, 2))
B = np.array([10, 20, 30])  # shape: (3,)
A + B

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 