In [1]:
import numpy as np

Arrays with Fixed Values

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [4]:
np.full((2, 2), fill_value=7.5)

array([[7.5, 7.5],
       [7.5, 7.5]])

Arrays with Uninitialized Values

In [5]:
np.empty((2, 4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261230e-306],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306]])

Arrays with Shape Based on Another Array

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]])

np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

Arrays with Regular Spacing

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.logspace(-1, 2, 4)

array([  0.1,   1. ,  10. , 100. ])

In [11]:
x = np.linspace(0, 1, 5)
y = np.linspace(1, 3, 3)
X, Y = np.meshgrid(x, y)

print(X)
print(Y)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]


Arrays with Random Values

In [12]:
np.random.seed(42)
np.random.random()

0.3745401188473625

In [13]:
rng = np.random.default_rng(42)
rng.random()

0.7739560485559633

In [14]:
np.random.seed(42)

In [15]:
np.random.random((2, 3))

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [16]:
np.random.randint(10, 20, size=(2, 4))

array([[17, 14, 13, 17],
       [17, 12, 15, 14]])

In [17]:
np.random.normal(loc=0.0, scale=1.0, size=(5,))

array([-0.58087813, -0.52516981, -0.57138017, -0.92408284, -2.61254901])

In [18]:
np.random.choice(['cat', 'dog', 'bird'], size=5, p=[0.5, 0.3, 0.2])

array(['cat', 'dog', 'cat', 'cat', 'cat'], dtype='<U4')

Building Matrices

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])