In [1]:
import numpy as np

In [2]:
x = np.array([1, 2])
y = np.array([3, 4])

np.dot(x, y)  # or x @ y

11

In [3]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[4,  2], 
              [-2, 1]])
A @ B

array([[ 0,  4],
       [ 4, 10]])

In [4]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
np.linalg.det(A)

-2.0000000000000004

In [6]:
np.linalg.solve(A, [1, 0])

array([-2. ,  1.5])

In [7]:
vals, vecs = np.linalg.eig(A)

print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
