In [1]:
import numpy as np

Indexing

In [2]:
x = np.array([10, 20, 30, 40])
x[0]

10

In [3]:
print(x[-1])  # Last element
print(x[-2])  # Second-to-last element

40
30


In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(A[0, 1])   # Element in first row, second column
print(A[2, -1])  # Element in third row, last column

2
9


In [5]:
A[1]

array([4, 5, 6])

In [6]:
T = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
T[1, 0, 1]  # Element at: second 2D block, first row, second column

6

Slicing

In [7]:
x = np.array([10, 20, 30, 40, 50])
x[1:4]  # Elements from index 1 to 3

array([20, 30, 40])

In [8]:
x[:3]  # Equivalent to x[0:3]

array([10, 20, 30])

In [9]:
x[::2]  # Every second element

array([10, 30, 50])

In [10]:
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])

In [11]:
A[1:3]  # Rows 1 and 2

array([[4, 5, 6],
       [7, 8, 9]])

In [12]:
A[:, 0]  # First column of all rows

array([ 1,  4,  7, 10])

In [13]:
A[1:3, 0:2]  # Rows 1-2 and columns 0-1

array([[4, 5],
       [7, 8]])

In [14]:
A[::2]  # Every second row

array([[1, 2, 3],
       [7, 8, 9]])

In [15]:
A[:, ::2]  # Every second column

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [16]:
A[-2:]  # Last two rows

array([[ 7,  8,  9],
       [10, 11, 12]])

In [17]:
A[:, -1]  # Last column

array([ 3,  6,  9, 12])

In [18]:
A[1, 1:]  # Elements from row 1, columns 1 to end

array([5, 6])

In [19]:
A[:2, 2]  # First two rows, column 2

array([3, 6])

In [20]:
x = np.array([10, 20, 30, 40, 50])
y = x[:2]  # Returns a view
y[:] = 0   # Modifies both x and y
print(x) 

[ 0  0 30 40 50]


Fancy Indexing

In [21]:
x = np.array([10, 20, 30, 40, 50])
x[[1, 3, 4]]  # Select elements at indices 1, 3, and 4

array([20, 40, 50])

In [22]:
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])
A[[0, 2]]  # Select rows 0 and 2

array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
A[:, [1, 2]]  # Select columns 1 and 2

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [24]:
A[[0, 1, 2], [2, 1, 0]]  # Elements at (0,2), (1,1), (2,0)

array([3, 5, 7])

In [25]:
x = np.array([10, 20, 30, 40, 50])
y = x[[0, 2, 4]]  # Returns a copy
y[:] = 0          # Modifies y only
print(x)          # Still unchanged

[10 20 30 40 50]


Boolean Masking

In [26]:
x = np.array([10, 20, 30, 40, 50])
mask = x > 25
x[mask]  # Elements greater than 25

array([30, 40, 50])

In [27]:
mask

array([False, False,  True,  True,  True])

In [28]:
x[x > 25]

array([30, 40, 50])

In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A % 2 == 0  # Boolean mask for even elements

array([[False,  True, False],
       [ True, False,  True]])

In [30]:
A[A % 2 == 0]

array([2, 4, 6])

In [31]:
x = np.array([10, 20, 30, 40, 50])
x[(x > 15) & (x < 45)]  # Elements between 15 and 45

array([20, 30, 40])

In [32]:
x = np.array([10, 20, 30, 40, 50])
y = x[x > 30]  # Returns a copy
y[:] = 0       # Modifies y only
print(x)       # Still unchanged

[10 20 30 40 50]


Conditional Selection with np.where

In [33]:
x = np.array([10, 20, 30, 40, 50])
np.where(x > 25)

(array([2, 3, 4], dtype=int64),)

In [34]:
x = np.array([10, 20, 30, 40, 50])
np.where(x > 25, 1, 0)

array([0, 0, 1, 1, 1])

In [35]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([100, 200, 300, 400, 500])
np.where(x > 25, x, y)

array([100, 200,  30,  40,  50])

In [36]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.where(A % 2 == 0, A, -1)  # Replace odd numbers with -1

array([[-1,  2, -1],
       [ 4, -1,  6]])

Assignments

In [37]:
x = np.array([10, 20, 30, 40, 50])
x[1:3] = [99, 88]
x

array([10, 99, 88, 40, 50])

In [38]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A[:, 1] = 0  # Set entire second column to 0
A

array([[1, 0, 3],
       [4, 0, 6]])

In [39]:
x = np.array([10, 20, 30, 40, 50])
x[x < 30] = 0  # Set elements less than 30 to zero
x

array([ 0,  0, 30, 40, 50])

In [40]:
x = np.array([10, 20, 30, 40, 50])
x = np.where(x > 40, 100, x)  # Replace elements > 40 with 100
x

array([ 10,  20,  30,  40, 100])

In [41]:
x = np.array([10, 20, 30, 40, 50])
x[[0, 2, 4]] = [1, 2, 3]
x

array([ 1, 20,  2, 40,  3])