In [1]:
import numpy as np

In [2]:
x = np.array([3, 1, 4, 2, 5])
print(np.sort(x))  # Create a new sorted array
print(x)  # Original unchanged

[1 2 3 4 5]
[3 1 4 2 5]


In [3]:
x.sort()  # Sort in place
print(x)

[1 2 3 4 5]


In [4]:
A = np.array([[3, 1, 4],
              [2, 5, 0]])

print(np.sort(A, axis=0))  # Sort each column
print(np.sort(A, axis=1))  # Sort each row

[[2 1 0]
 [3 5 4]]
[[1 3 4]
 [0 2 5]]


In [5]:
A = np.array([[3, 1, 4],
              [2, 5, 0]])

print(np.argsort(A, axis=0))  # indices to sort each column
print(np.argsort(A, axis=1))  # indices to sort each row

[[1 0 1]
 [0 1 0]]
[[1 0 2]
 [2 0 1]]


In [6]:
x = np.array([5, 2, 3, 2])
labels = np.array(['a', 'b', 'c', 'd'])  # Associate labels with each element
indices = np.argsort(x, kind='mergesort')
print(x[indices])       # Sorted values
print(labels[indices])  # Corresponding original labels

[2 2 3 5]
['b' 'd' 'c' 'a']
