In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y

array([5, 7, 9])

In [3]:
np.add(x, y)

array([5, 7, 9])

In [4]:
result = np.empty_like(x)
np.add(x, y, out=result)
result

array([5, 7, 9])

Performance Comparison to a Python Loop

In [5]:
n = 10**6
a = np.random.rand(n)
b = np.random.rand(n)

# NumPy ufunc
%timeit a + b

# Pure Python loop
%timeit [a[i] + b[i] for i in range(n)]

2.51 ms ± 186 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
327 ms ± 13.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Arithemtic Functions

In [6]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x * y)
print(x ** 2)
print(y // x)

[ 4 10 18]
[1 4 9]
[4 2 2]


Comparison Functions

In [7]:
x = np.array([1, 2, 3])
y = np.array([2, 2, 2])

print(x == y)
print(x < y)
print(x >= y)

[False  True False]
[ True False False]
[False  True  True]


In [8]:
a = np.array([0.1 + 0.2])
b = np.array([0.3])

print(a == b)  # May be False due to floating-point error
print(np.isclose(a, b))  # Correct way to compare

[False]
[ True]


In [9]:
np.allclose(a, b)

True

Logical Functions

In [10]:
x = np.array([True, False, True])
y = np.array([False, False, True])

print(x & y)  # AND
print(x | y)  # OR
print(~x)     # NOT

[False False  True]
[ True False  True]
[False  True False]


Mathematical Functions

In [11]:
x = np.array([1, 4, 9, 16])

print(np.sqrt(x))       # Square root
print(np.log(x))        # Natural log
print(np.sin(x))        # Sine (input in radians)
print(np.exp(x))        # Exponential function
print(np.sign(x - 9))   # Sign: -1 if < 0, 0 if 0, 1 if > 0

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[-1 -1  0  1]


Bitwise Functions

In [12]:
# Logical AND with Boolean arrays
a_bool = np.array([True, False, True])
b_bool = np.array([False, False, True])
print(a_bool & b_bool)

# Bitwise AND with integer arrays
a_int = np.array([1, 2, 3])   # binary: 001, 010, 011
b_int = np.array([2, 2, 1])   # binary: 010, 010, 001
print(a_int & b_int)

[False False  True]
[0 2 1]


In [13]:
x = np.array([1, 2, 3])
y = np.array([2, 2, 1])

print(x & y)          # bitwise AND
print(x | y)          # bitwise OR
print(x ^ y)          # bitwise XOR
print(~x)             # bitwise NOT
print(np.left_shift(x, 1))   # equivalent to x * 2
print(np.right_shift(x, 1))  # equivalent to x // 2

[0 2 1]
[3 2 3]
[3 0 2]
[-2 -3 -4]
[2 4 6]
[0 1 1]


Set Functions

In [14]:
x = np.array([1, 2, 2, 3, 4])
y = np.array([3, 4, 4, 5, 6])

print(np.unique(x))
print(np.intersect1d(x, y))
print(np.union1d(x, y))
print(np.isin(x, y))

[1 2 3 4]
[3 4]
[1 2 3 4 5 6]
[False False False  True  True]


In [15]:
x = np.array([4, 1, 2, 1, 5, 2, 1])

values, counts = np.unique(x, return_counts=True)

print("Values:", values)
print("Counts:", counts)

Values: [1 2 4 5]
Counts: [3 2 1 1]
